services:
  db:
    image: postgres:17
    container_name: paginakinesiologia-db
    environment:
      POSTGRES_DB: db_paginakinesiologia
      POSTGRES_USER: user_paginakinesiologia
      POSTGRES_PASSWORD: 'barca'
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # ðŸ‘ˆ (opcional, Ãºtil si quieres conectarte con PgAdmin o DBeaver)
    restart: always  # ðŸ‘ˆ asegura que el contenedor se reinicie si se cae

  web:
    build: .
    container_name: paginakinesiologia-web
    command: gunicorn PaginaKinesiologia.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
      - static_volume:/vol/staticfiles
      - media_volume:/vol/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

volumes:
  db_data:
  static_volume:
  media_volume:
